/*
 * Dictionnaire de traduction du CONTENU (FR → EN) : événements, objets,
 * ennemis, métiers, traits… Les clés sont les chaînes françaises EXACTES du
 * jeu (voir GameContext.tsx). Toute chaîne absente retombe sur le français
 * (voir tc() dans lang.ts), donc le jeu n'est jamais cassé pendant qu'on
 * complète la traduction, par lots.
 */
export const CONTENT_EN: Record<string, string> = {
  // ============ ENNEMIS ============
  'Commerçant Furieux': 'Furious Shopkeeper',
  'Il vous a pris la main dans le sac. Et il a de la poigne.': 'He caught you red-handed. And he\'s got a grip.',
  'Rat Géant': 'Giant Rat',
  'Un rat de la taille d\'un chihuahua. Il n\'a pas peur.': 'A rat the size of a chihuahua. It\'s not scared.',
  'Mouette Furibonde': 'Furious Seagull',
  'Elle veut votre sandwich. Elle aura votre sandwich.': 'It wants your sandwich. It will have your sandwich.',
  'Chien Errant': 'Stray Dog',
  'Un molosse sans collier. Ses crocs brillent au clair de lune.': 'A collarless brute. Its fangs gleam in the moonlight.',
  'Pigeon Alpha': 'Alpha Pigeon',
  'Le chef du gang de pigeons. Il roucoule avec menace.': 'The leader of the pigeon gang. It coos menacingly.',
  'Voyou du Coin': 'Local Thug',
  'Un type louche qui veut votre spot. Négociation impossible.': 'A shady guy who wants your spot. No negotiating.',
  'Agent de Sécurité': 'Security Guard',
  'Il fait du zèle. Beaucoup de zèle.': 'He\'s overzealous. Very overzealous.',
  'Chat de Gouttière': 'Alley Cat',
  'Petit mais vicieux. Ses griffes sont des rasoirs.': 'Small but vicious. Its claws are razors.',
  'Raton Laveur': 'Raccoon',
  'Il fouille VOTRE poubelle. L\'affront.': 'It\'s rummaging through YOUR trash. The nerve.',
  'Corbeau Géant': 'Giant Crow',
  'Noir comme la nuit, méchant comme le jour.': 'Black as night, mean as day.',
  'Ivrogne Agressif': 'Aggressive Drunk',
  'Il titube mais frappe fort. Très fort.': 'He staggers but hits hard. Very hard.',
  'Vigile Zélé': 'Zealous Bouncer',
  'Badge, lampe torche, ego surdimensionné.': 'Badge, flashlight, oversized ego.',
  'Cygne Furieux': 'Furious Swan',
  'Élégant mais mortel. Ne jamais sous-estimer un cygne.': 'Elegant but deadly. Never underestimate a swan.',
  'Clown Sinistre': 'Sinister Clown',
  'Son rire résonne dans la nuit. Personne ne rit avec lui.': 'His laugh echoes in the night. Nobody laughs with him.',
  'Écureuil Enragé': 'Rabid Squirrel',
  'Petit, rapide, et il veut vos noisettes. Vous avez pas de noisettes.': 'Small, fast, and it wants your nuts. You have no nuts.',
  'Oie Territoriale': 'Territorial Goose',
  'HONK. Elle défend son territoire avec une rage ancestrale.': 'HONK. It defends its turf with ancestral rage.',
  'Canard Psychopathe': 'Psycho Duck',
  'Coin coin... COIN COIN ! Il charge !': 'Quack quack... QUACK QUACK! It charges!',
  'Coq de Combat': 'Fighting Rooster',
  'Réveillé à 4h du matin. Et il est furieux.': 'Awake at 4 a.m. And it\'s furious.',
  'Chat Territorial': 'Territorial Cat',
  'Ce coin est à LUI. Et il va vous le prouver.': 'This corner is HIS. And he\'ll prove it.',
  'Mouette Géante': 'Giant Seagull',
  'La mère de toutes les mouettes. Envergure impressionnante.': 'The mother of all seagulls. Impressive wingspan.',
  'Raton Laveur Alpha': 'Alpha Raccoon',
  'Le boss des ratons. Il porte un masque naturel de bandit.': 'The raccoon boss. It wears a natural bandit mask.',
  'Chat Sauvage': 'Wild Cat',
  'Pas de collier, pas de maître, pas de pitié.': 'No collar, no master, no mercy.',

  // ============ MÉTIERS ============
  'Ancien Comptable': 'Former Accountant',
  'Les chiffres, ça le connaît. Les poubelles, un peu moins.': 'He knows numbers. Trash cans, less so.',
  'Ancien Ouvrier': 'Former Laborer',
  'Des mains en or et un dos en compote.': 'Golden hands and a wrecked back.',
  'Ancien Professeur': 'Former Teacher',
  'Il corrige encore les fautes sur les panneaux.': 'He still corrects typos on street signs.',
  'Ancien Sommelier': 'Former Sommelier',
  'Peut distinguer un Bordeaux d\'un jus de poubelle. Parfois.': 'Can tell a Bordeaux from bin juice. Sometimes.',
  'Ancien Cascadeur': 'Former Stuntman',
  'Tombe de haut. Littéralement et figurativement.': 'Falls from great heights. Literally and figuratively.',
  'Ancien Informaticien': 'Former IT Guy',
  'Cherche encore le WiFi gratuit.': 'Still looking for free WiFi.',
  'Ancien Cuisinier': 'Former Cook',
  'Transforme un rat en ratatouille.': 'Turns a rat into ratatouille.',
  'Ancien Infirmier': 'Former Nurse',
  'Se soigne avec des feuilles de journal.': 'Heals himself with newspaper.',
  'Ancien Artiste': 'Former Artist',
  'Son art n\'a jamais été compris. Même par lui.': 'His art was never understood. Not even by him.',
  'Ancien Militaire': 'Former Soldier',
  'Dort debout et mange n\'importe quoi.': 'Sleeps standing up and eats anything.',
  'Ancien Bibliothécaire': 'Former Librarian',
  'Connaît tous les recoins de la ville.': 'Knows every nook of the city.',
  'Ancien Vendeur de Voitures': 'Former Car Salesman',
  'Peut vendre un carton mouillé comme un loft.': 'Can sell a soggy box like a loft.',
  'Ancien Jardinier': 'Former Gardener',
  'Fait pousser des tomates dans une chaussure.': 'Grows tomatoes in a shoe.',
  'Ancien Avocat': 'Former Lawyer',
  'Connaît ses droits. Et ceux des pigeons.': 'Knows his rights. And the pigeons\' rights.',
  'Ancien Musicien': 'Former Musician',
  'Son harmonica a connu des jours meilleurs.': 'His harmonica has seen better days.',

  // ============ TRAITS ============
  'Estomac d\'Acier': 'Iron Stomach',
  'Immunisé à la nourriture périmée': 'Immune to spoiled food',
  'Optimiste Né': 'Born Optimist',
  'La santé mentale remonte plus vite': 'Mental health recovers faster',
  'Ami des Pigeons': 'Pigeon Friend',
  'Les oiseaux apportent des objets': 'Birds bring you items',
  'Sommeil de Plomb': 'Heavy Sleeper',
  'Récupère plus vite en dormant': 'Recovers faster while sleeping',
  'Nez Sensible': 'Sensitive Nose',
  'Détecte les dangers, malus dignité si sale': 'Senses danger, dignity penalty if dirty',
  'Insomniaque': 'Insomniac',
  'Moins de sommeil requis, mental fragile': 'Needs less sleep, fragile mind',
  'Paranoïaque': 'Paranoid',
  'Pas de vol en dormant, stress élevé': 'No theft while sleeping, high stress',
  'Main Verte': 'Green Thumb',
  'Fait pousser des choses dans des pots': 'Grows things in pots',
  'Charismatique': 'Charismatic',
  'Les passants donnent plus facilement': 'Passers-by give more easily',
  'Os en Mousse': 'Foam Bones',
  'Subit plus de dégâts physiques': 'Takes more physical damage',
  'Métabolisme Rapide': 'Fast Metabolism',
  'Guérit vite, mais toujours faim': 'Heals fast, but always hungry',
  'Collectionneur': 'Collector',
  'Bonus moral si inventaire plein': 'Morale bonus when inventory is full',
  'Phobie des Rats': 'Rat Phobia',
  'Panique en zone industrielle': 'Panics in the industrial zone',
  'Haleine Redoutable': 'Dreadful Breath',
  'Bonus combat, malus social': 'Combat bonus, social penalty',
  'Agile': 'Agile',
  'Excellente capacité de fuite': 'Excellent at fleeing',
  'Résistant au Froid': 'Cold-Resistant',
  'Dort dehors sans couverture': 'Sleeps outside without a blanket',
  'Bricoleur du Dimanche': 'Weekend Handyman',
  'Artisanat moins coûteux': 'Cheaper crafting',
  'Sens de l\'Orientation': 'Sense of Direction',
  'Ne se perd jamais': 'Never gets lost',

  // ============ BOUTIQUES ============
  'Boulangerie du Coin': 'Corner Bakery',
  'Le pain de la veille, mais à prix cassé.': 'Yesterday\'s bread, at a knockdown price.',
  'Épicerie de Nuit': 'Night Grocery',
  'Ouverte 24h/24. Prix majorés, mais pratique.': 'Open 24/7. Marked-up prices, but handy.',
  'Pharmacie Populaire': 'Discount Pharmacy',
  'Soins basiques à prix réduit.': 'Basic care at low prices.',
  'Marché aux Puces': 'Flea Market',
  'Vêtements et objets de seconde main.': 'Second-hand clothes and goods.',
  'Le Brocanteur Louche': 'The Shady Junk Dealer',
  'Il vend de tout. Surtout du n\'importe quoi.': 'He sells everything. Mostly junk.',
  'Fontaine Publique': 'Public Fountain',
  'Gratuite. Enfin presque.': 'Free. Well, almost.',
  'Distributeur Automatique': 'Vending Machine',
  'Accepte les pièces. Parfois.': 'Takes coins. Sometimes.',
  'Kebab du Quartier': 'Neighborhood Kebab',
  'Le meilleur rapport qualité-prix de la ville.': 'The best value in town.',
  'Laverie Automatique': 'Laundromat',
  'Lavez vos vêtements. Retrouvez votre dignité.': 'Wash your clothes. Recover your dignity.',
  'Herboriste du Parc': 'Park Herbalist',
  'Remèdes naturels et tisanes.': 'Natural remedies and herbal teas.',

  // ============ OBJETS ============
  'Pain rassis': 'Stale Bread', 'Dur comme la vie, mais nourrissant.': 'Hard as life, but filling.',
  'Croissant du matin': 'Morning Croissant', 'Encore tiède. Un luxe.': 'Still warm. A luxury.',
  'Sandwich jambon-beurre': 'Ham & Butter Sandwich', 'Le classique indémodable.': 'The timeless classic.',
  'Gâteau sec': 'Dry Biscuit', 'Croquant et réconfortant.': 'Crunchy and comforting.',
  'Bouteille d\'eau': 'Bottle of Water', 'De l\'eau. Juste de l\'eau. C\'est déjà bien.': 'Water. Just water. That\'s already something.',
  'Canette de soda': 'Can of Soda', 'Sucré, pétillant, et plein de bulles.': 'Sweet, fizzy, and full of bubbles.',
  'Conserve de raviolis': 'Can of Ravioli', 'Le repas du roi (du carton).': 'A meal fit for a (cardboard) king.',
  'Bière pas chère': 'Cheap Beer', 'Réchauffe le corps, embrume l\'esprit.': 'Warms the body, fogs the mind.',
  'Briquet': 'Lighter', 'Indispensable pour les nuits froides.': 'Essential for cold nights.',
  'Parapluie cassé': 'Broken Umbrella', 'Ne protège que la moitié. Mais quelle moitié !': 'Only covers half. But what a half!',
  'Boîte de pansements': 'Box of Bandages', 'Pour les petits bobos du quotidien.': 'For everyday little scrapes.',
  'Aspirine': 'Aspirin', 'Contre les maux de tête et les coups.': 'For headaches and beatings.',
  'Sirop pour la toux': 'Cough Syrup', 'Goût horrible, efficacité prouvée.': 'Horrible taste, proven effect.',
  'Crème solaire périmée': 'Expired Sunscreen', 'Périmée depuis 2019, mais ça protège un peu.': 'Expired since 2019, but it protects a bit.',
  'Manteau d\'occasion': 'Second-hand Coat', 'Chaud et presque propre.': 'Warm and almost clean.',
  'Chaussures usées': 'Worn Shoes', 'Trouées mais fonctionnelles.': 'Holey but functional.',
  'Bonnet en laine': 'Wool Hat', 'Tricoté main. Couleur douteuse.': 'Hand-knitted. Questionable color.',
  'Sac à dos troué': 'Holey Backpack', 'Augmente la capacité de transport. Enfin, un peu.': 'Increases carrying capacity. A little, anyway.',
  'Batte de baseball fissurée': 'Cracked Baseball Bat', 'Arme lourde : même un coup mal ajusté fait mal. Elle a connu des crânes.': 'Heavy weapon: even a sloppy hit hurts. It\'s met a few skulls.',
  'Couteau rouillé': 'Rusty Knife', 'Arme précise : critiques dévastateurs, mais il faut viser juste. Tétanos en bonus.': 'Precise weapon: devastating crits, but you must aim well. Tetanus included.',
  'Gilet de protection': 'Protective Vest', 'Ancien gilet de chantier. Absorbe les coups.': 'Old construction vest. Absorbs blows.',
  'Lampe torche': 'Flashlight', 'Les piles sont presque mortes.': 'The batteries are nearly dead.',
  'Eau de la fontaine': 'Fountain Water', 'Gratuite et fraîche. Un miracle urbain.': 'Free and fresh. An urban miracle.',
  'Café de la machine': 'Vending-Machine Coffee', 'Imbuvable mais ça réveille.': 'Undrinkable but it wakes you up.',
  'Barre chocolatée': 'Chocolate Bar', 'Calories et réconfort en barre.': 'Calories and comfort in a bar.',
  'Paquet de chips': 'Bag of Chips', 'Salé, croustillant, addictif.': 'Salty, crunchy, addictive.',
  'Kebab-frites': 'Kebab & Fries', 'Le festin des rois. Du carton.': 'A feast fit for kings. Of cardboard.',
  'Cornet de frites': 'Cone of Fries', 'Grasses à souhait. Délicieuses.': 'Greasy as can be. Delicious.',
  'Boisson fraîche': 'Cold Drink', 'Pour faire passer le kebab.': 'To wash down the kebab.',
  'Lavage de vêtements': 'Clothes Wash', 'Propre pendant au moins 2 jours.': 'Clean for at least 2 days.',
  'Tisane calmante': 'Calming Herbal Tea', 'Apaise les nerfs et réchauffe le cœur.': 'Soothes the nerves and warms the heart.',
  'Onguent de plantes': 'Herbal Ointment', 'Ça pique, ça gratte, mais ça soigne.': 'It stings, it itches, but it heals.',
  'Bouquet de fleurs sauvages': 'Bouquet of Wildflowers', 'Pour le moral. Ou pour revendre.': 'For your morale. Or to resell.',
};
